development:
  adapter: postgresql
  encoding: unicode
  database: parks_development
  pool: 5
  username: mchliakh
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: parks_test
  pool: 5
  username: mchliakh
  password:
